In [1]:
import numpy as np 
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 4]
 [5 8 7]]


In [3]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
#creating an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.33600948 0.68207536]
 [0.04288973 0.10171681]]
